
export const CONTRACT_ADDRESS = "0x4BcAafe9c4d2C711f5447277dcB2eDF1143e961D";
export const CHAIN_ID = 56;
export const CHAIN_ID_HEX = "0x38";
export const RPC_URL = "https://bsc-dataseed.binance.org/";

export const CONTRACT_ABI = [
  {"inputs":[],"stateMutability":"nonpayable","type":"constructor"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint8","name":"newLevel","type":"uint8"}],"name":"AccountActivated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":true,"internalType":"address","name":"affiliateParent","type":"address"},{"indexed":true,"internalType":"address","name":"binaryParent","type":"address"},{"indexed":false,"internalType":"bool","name":"binaryGroup","type":"bool"}],"name":"AccountRegistered","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"agent","type":"address"}],"name":"AgentActivated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"DepositBalance","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"method","type":"string"},{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"InternalTransfer","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"rewardsName","type":"string"},{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"newValue","type":"uint256"}],"name":"Rewards","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"oldBalance","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"newBalance","type":"uint256"}],"name":"TokenBalance","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"WithdrawBalance","type":"event"},
  {"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"activateAgent","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"activateRank","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"affiliates","outputs":[{"internalType":"address","name":"parent","type":"address"},{"internalType":"address","name":"agent","type":"address"},{"internalType":"uint256","name":"totalDirect","type":"uint256"},{"internalType":"uint8","name":"level","type":"uint8"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"binaries","outputs":[{"internalType":"address","name":"parent","type":"address"},{"internalType":"address","name":"leftAddress","type":"address"},{"internalType":"address","name":"rightAddress","type":"address"},{"internalType":"uint256","name":"leftVolume","type":"uint256"},{"internalType":"uint256","name":"rightVolume","type":"uint256"},{"internalType":"uint256","name":"coolDown","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"collectBinaryRewards","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"collectPassiveRewards","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"depositFBMX","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"depositUSDT","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"emergencyWithdrawal","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_user","type":"address"},{"internalType":"uint256","name":"_startIndex","type":"uint256"},{"internalType":"uint256","name":"_count","type":"uint256"}],"name":"getChildren","outputs":[{"internalType":"address[]","name":"childrenBatch","type":"address[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getContractStats","outputs":[{"internalType":"uint256","name":"_totalUsers","type":"uint256"},{"internalType":"uint256","name":"_totalAgents","type":"uint256"},{"internalType":"uint256","name":"_totalUSDT","type":"uint256"},{"internalType":"uint256","name":"_totalFBMX","type":"uint256"},{"internalType":"uint256","name":"_totalDeposits","type":"uint256"},{"internalType":"uint256","name":"_totalRewards","type":"uint256"},{"internalType":"uint256","name":"_totalWithdrawals","type":"uint256"},{"internalType":"uint256","name":"_totalMarketingFunding","type":"uint256"},{"internalType":"uint256","name":"_totalProjectFunding","type":"uint256"},{"internalType":"uint256","name":"_totalLiquidityFunding","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_totalEquity","type":"uint256"},{"internalType":"uint256","name":"_totalIncome","type":"uint256"}],"name":"getEquity","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},
  {"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"getPassiveReward","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_passiveEquity","type":"uint256"},{"internalType":"uint256","name":"_referralIncome","type":"uint256"}],"name":"getPercentage","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},
  {"inputs":[{"internalType":"address","name":"_user","type":"address"},{"internalType":"uint8","name":"_options","type":"uint8"}],"name":"getPlacement","outputs":[{"internalType":"address","name":"_address","type":"address"},{"internalType":"bool","name":"_position","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"getUpgradeAmount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"_userLevel","type":"uint8"},{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"getWithdrawAmount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"lastCallBlock","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"lastCallTime","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"passives","outputs":[{"internalType":"uint256","name":"totalPassive","type":"uint256"},{"internalType":"uint256","name":"totalEquity","type":"uint256"},{"internalType":"uint256","name":"coolDown","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_referrer","type":"address"},{"internalType":"uint8","name":"_group","type":"uint8"}],"name":"register","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"tokenBalance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"wallets","outputs":[{"internalType":"uint256","name":"balance","type":"uint256"},{"internalType":"uint256","name":"capping","type":"uint256"},{"internalType":"uint256","name":"totalIncome","type":"uint256"},{"internalType":"uint256","name":"coolDown","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"withdrawBalance","outputs":[],"stateMutability":"nonpayable","type":"function"}
];
